SmartShop.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using SmartShop.DataLib.Models.Constants;
using SmartShop.DataLib.Models.Data;
using SmartShop.Web.Hubs;
using SmartShop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SmartShop.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly SmartShopDbContext _db;
        private readonly IHubContext<OrderCreatedNotificationHub> _hubContext;

        public OrderController(SmartShopDbContext db, IHubContext<OrderCreatedNotificationHub> hubContext)
        {
            _db = db;
            this._hubContext = hubContext;
        }

        //order index
         public IActionResult Index()
         {
             var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
             var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
             var CustomerId = Customer.CustomerId;
             OrderVM orderVM = new OrderVM()
             {



                 Orders = _db.Orders
                 .Where(x => x.CustomerId.Equals(CustomerId))
                 .Include(x => x.OrderDetails)
                 .ThenInclude(x => x.Product)
                 .ThenInclude(x=>x.ProductPrices)
                 .ToList(),

                 Total = _db.OrderDetails
                 .Where(x =>x.OrderId.Equals(x.OrderId))
                 .Sum(x => x.ProductPrice * x.Quantity),
             };
             return View(orderVM);
         }

        //order details

         public IActionResult OrderDetails(int id)
         {
            var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
            var CustomerId = Customer.CustomerId;
            var order = _db.Orders.Where(x => x.OrderId.Equals(id))
                .Include(x => x.OrderDetails)
                .ThenInclude(x=>x.Product)
            .FirstOrDefault();

            return View(order);
        }



        //order store
         [HttpPost]
         public IActionResult OrderStore(CheckoutVM model)
         {
             if (ModelState.IsValid)
             {
                //user id
                 var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                //customer
                 var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
                //customer id
                 var CustomerId = Customer.CustomerId;

                //order
                var NewOrder = new Order()
                {

                    PaymentName = model.PaymentName,
                    Comment = model.Message,
                    CustomerId = CustomerId,
                    OrderDate = DateTime.Now,
                    ShippingId = model.ShippingId,
                    IsConfirmed = false,
                    TrxId = model.TrxId,
                    OrderStatus = OrderStatus.Pending




                 };
       
                 _db.Orders.Add(NewOrder);
                 _db.SaveChanges();
                this.SendNotification(NewOrder).ContinueWith(t => { });

                //check customer details
                var CheckCustomer = _db.Customers
                     .Where(x => x.CustomerId == CustomerId)
                      .Where(x => x.CustomerName == null)
                       .Where(x => x.Address == null)
                        .Where(x => x.Phone == null)
                     .FirstOrDefault();
                 if (CheckCustomer != null)
                 {
                     CheckCustomer.Address = model.Address;
                     CheckCustomer.CustomerName = model.CustomerName;
                     CheckCustomer.Phone = model.Phone;
                     _db.SaveChanges();
                 }

                 //all carts
                 var Carts = _db.Carts.Where(x => x.CustomerId.Equals(CustomerId)).ToList();
                 if (Carts != null)
                 {
                     foreach (var c in Carts)
                     {
                        //create order details
                        var orderDetails = new OrderDetail()
                        {
                            OrderId = NewOrder.OrderId,
                            ProductId = c.ProductId,
                            Quantity = c.Quantity,
                            ProductPrice = c.ProductPrice,
                        };
                        _db.OrderDetails.Add(orderDetails);
                        _db.SaveChanges();

                        //delete cart
                        _db.Entry(c).State = EntityState.Deleted;

                        _db.SaveChanges();
                     }
                 }



                 return RedirectToAction("Index","User");

             }

             return View(model);


         }
       
        
        private async Task SendNotification(Order NewOrder)
        {
            await this._hubContext.Clients.All.SendAsync("orderCreated", new NotificationMessage { OrderId = NewOrder.OrderId, CustomerId = NewOrder.CustomerId, Message = "Created" });
        }
    }
}

SmartShop.Web/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartShop.DataLib.Models.Data;
using SmartShop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SmartShop.Web.Controllers
{
    public class ReviewController : Controller
    {
        private readonly SmartShopDbContext _db;
        public ReviewController(SmartShopDbContext db)
        {
            this._db = db;
        }

        //review index
        public IActionResult Index(int id)
        {
            var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
            var CustomerId = Customer.CustomerId;
            var Review = _db.Reviews.Where(x => x.CustomerId.Equals(CustomerId)).FirstOrDefault();
            var Product = _db.Products.Where(x => x.ProductId == id).FirstOrDefault();
            var reviewVM = new ReviewVM()
            {
                Product =Product,
                Review = Review,
        };



            return View(reviewVM);
        }
        //add review
        public IActionResult ReviewStore(ReviewVM model)
        {
            if (ModelState.IsValid)
            {
                var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
                var CustomerId = Customer.CustomerId;
                var checkReview = _db.Reviews
                    .Where(x => x.ProductId.Equals(model.ProductId))
                    .Where(x => x.CustomerId.Equals(CustomerId)).FirstOrDefault();
                if (checkReview != null)
                {
                    var Review = _db.Reviews.Where(x => x.ProductId.Equals(model.ProductId)).Where(x => x.CustomerId.Equals(CustomerId)).FirstOrDefault();

                    if (Review != null)
                    {
                        Review.Comment = model.Comment;
                        Review.Rating = model.Rating;
                        _db.SaveChanges();
                        return RedirectToAction("Index", "Order");
                    }
                }
                else
                {
                    var Review = new Review()
                    {
                        Rating = model.Rating,
                        Comment = model.Comment,
                        ProductId = model.ProductId,
                        CustomerId = CustomerId
                    };
                    _db.Reviews.Add(Review);
                    _db.SaveChanges();
                    return RedirectToAction("Index", "Order");

                }

        
     
                return RedirectToAction("Index", "Order");
            }
            return RedirectToAction("Index", "Order");
        }


     
    }
}

SmartShop.Web/Views/Order/OrderDetails.cshtml
@model Order
    <div class="container">
        <div class="col-lg-10 mx-auto mt-5">
            <div class="card">
                <div class="card-header"><strong>#0000 @Model.OrderId</strong></div>
                <div class="card-body p-0 table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>

                                <th scope="col">Product Name</th>
                                <th scope="col">Price</th>

                                <th scope="col" width="14%">Qty</th>
                                <th scope="col">Sub Total</th>


                            </tr>
                        </thead>
                        <tbody>
                            @{
                                decimal total = 0;
                            }
                            @foreach (var c in Model.OrderDetails)
                            {

                                <tr>
                                    <td>@c.Product.ProductName</td>

                                    <td>    $@String.Format("{0:0.00}", c.ProductPrice)</td>
                                    <td>@c.Quantity</td>
                                    <td>
                                        @{
                                            var subtotal = c.ProductPrice * c.Quantity;
                                            total = total + subtotal;
                                        }

                                        $@String.Format("{0:0.00}", @subtotal)

                                    </td>

                                    @if (c.Order.OrderStatus.Equals(6))
                                    {
                                        <td><a class="btn btn-info rounded-0 btn-sm" asp-action="Index" asp-controller="Review" asp-route-Id="@c.ProductId">Review</a></td>

                                    }
                                </tr>

                            }

                            <tr>
                                <td></td>
                                <td></td>
                                <td>Total</td>
                                <td>
                                    <p>
                                        <strong>

                                            $@String.Format("{0:0.00}", total)
                                        </strong>
                                    </p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
                <div class="card-body">
                                                <h4>Timeline</h4>
                                                <ul class="timeline">



                                                    <li class=@(
                                                                        Convert.ToInt32( Model.OrderStatus )==1 ||
                                                                         Convert.ToInt32( Model.OrderStatus )==2 ||
                                                                          Convert.ToInt32( Model.OrderStatus )==3 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==4 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==5 ||
                                                                        Convert.ToInt32( Model.OrderStatus )==6 ? "active" : ""
                                                        )>
                                                        <h6>PENDING</h6>
                                                        <p class="mb-0 text-muted">Your is pending now</p>
                                                        <o class="text-muted">
                                                            21 March, 2014
                                                        </o>
                                                    </li>

                                                    <li class=@(

                                                                         Convert.ToInt32( Model.OrderStatus )==2 ||
                                                                          Convert.ToInt32( Model.OrderStatus )==3 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==4 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==5 ||
                                                                        Convert.ToInt32( Model.OrderStatus )==6 ? "active" : ""
                                                        )>
                                                        <h6>CONFIRMED</h6>
                                                        <p class="mb-0 text-muted">Your order has been confirmed </p>
                                                        <o class="text-muted">
                                                            21 March, 2014
                                                        </o>
                                                    </li>

                                                    <li class=@(


                                                                          Convert.ToInt32( Model.OrderStatus )==3 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==4 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==5 ||
                                                                        Convert.ToInt32( Model.OrderStatus )==6 ? "active" : ""
                                                        )>
                                                        <h6>PAID</h6>
                                                        <p class="mb-0 text-muted">Your payment status paid</p>
                                                        <o class="text-muted">
                                                            21 March, 2014
                                                        </o>
                                                    </li>

                                                    <li class=@(


                                                                           Convert.ToInt32( Model.OrderStatus )==4 ||
                                                                           Convert.ToInt32( Model.OrderStatus )==5 ||
                                                                        Convert.ToInt32( Model.OrderStatus )==6 ? "active" : ""
                                                        )>
                                                        <h6>PICKED</h6>
                                                        <p class="mb-0 text-muted">Your product has been picked</p>
                                                        <o class="text-muted">
                                                            21 March, 2014
                                                        </o>
                                                    </li>
                                                    <li class=@(



                                                                           Convert.ToInt32( Model.OrderStatus )==5 ||
                                                                        Convert.ToInt32( Model.OrderStatus )==6 ? "active" : ""
                                                        )>
                                                        <h6>ON THE WAY</h6>
                                                        <p class="mb-0 text-muted">Your product on the way/</p>
                                                        <o class="text-muted">
                                                            21 March, 2014
                                                        </o>
                                                    </li>
                                                    <li class=@(


                                                              
                                                                        Convert.ToInt32( Model.OrderStatus )==6 ? "active" : ""
                                                        )>
                                                        <h6>DELIVERED</h6>
                                                        <p class="mb-0 text-muted">Your product has been delivered.</p>
                                                        <o class="text-muted">
                                                            21 March, 2014
                                                        </o>
                                                    </li>


                                                </ul>
                                            </div>
        </div>
    </div>