SmartShop.Web/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartShop.DataLib.Models.Data;
using SmartShop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SmartShop.Web.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
   
        readonly SmartShopDbContext _db = null;

        private readonly INotyfService _notyf;


        public CartController(SmartShopDbContext db, INotyfService notyf)
        {
            this._db = db;
            _notyf = notyf;

        }
        //show all cart
         public IActionResult Index()
         {
      
             var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
             var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
             var CustomerId = Customer.CustomerId;
             var Carts = _db.Carts
                .Where(x => x.CustomerId.Equals(CustomerId))
                .Include(x => x.Product)
                .Include(x => x.Product.ProductImages)
                .Include(x => x.Product.ProductPrices)
                .Include(x => x.Product.Brand)
                .ToList();
             var cartVM = new CartVM()
             {         
                   Carts = Carts,
                    Total = _db.Carts
                    .Where(x => x.CustomerId.Equals(CustomerId)).Sum(x=>x.ProductPrice* x.Quantity),
             };
             return View(cartVM);
         }

        //add to cart
         [HttpGet]
         public IActionResult AddToCart(ProductViewVM model)
         {
   
            //user id
             var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            //customer
             var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
            //customer id
             var CustomerId = Customer.CustomerId;
            //product price
            var ProductPrice = model.Price;

            //product 
             var product = _db.Products.Where(x => x.ProductId.Equals(model.ProductId)).FirstOrDefault();
            //check product
             var checkProduct = _db.Carts.Where(x => x.CustomerId.Equals(CustomerId)).Where(x => x.ProductId.Equals(model.ProductId)).FirstOrDefault();
             if (checkProduct != null)
             {

                 checkProduct.Quantity = checkProduct.Quantity + 1;

                 _db.SaveChanges();
                 _notyf.Success("Product added to your card", 2);
                 var total_cart = _db.Carts.Where(x => x.CustomerId.Equals(CustomerId)).Count();
                Json(total_cart);
                return RedirectToAction("Index");
            }
             else
             {
                 var cart = new Cart()
                 {
                     CustomerId = CustomerId,
                     ProductId = model.ProductId,
                     Quantity = 1,
                     ProductPrice= model.Price,
                 };
                 _db.Carts.Add(cart);
             
                 _db.SaveChanges();
                 _notyf.Success("Product added to your card", 2);
                 var total_cart = _db.Carts.Where(x => x.CustomerId.Equals(CustomerId)).Count();
                return RedirectToAction("Index");

            }

         }

        //remove cart
          public IActionResult RemoveCart(int id)
          {
              var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
              var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
              var CustomerId = Customer.CustomerId;

              var carts = _db.Carts.Where(x => x.CustomerId.Equals(CustomerId))
                  .Where(x => x.ProductId.Equals(id)).FirstOrDefault();


              _db.Entry(carts).State = EntityState.Deleted;

              _db.SaveChanges();
              _notyf.Success("Cart remove from your cart", 3);
              return RedirectToAction("Index");
          }

        //add cart qty
         public IActionResult AddQuantity(CartVM model, int id)
         {
             var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
             var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
             var CustomerId = Customer.CustomerId;

             var checkProduct = _db.Carts.Where(x => x.CustomerId.Equals(CustomerId)).Where(x => x.ProductId.Equals(id)).FirstOrDefault();
             if (checkProduct != null)
             {

                 checkProduct.Quantity = model.Quantity;

                 _db.SaveChanges();
                 return RedirectToAction("Index");
             }
             return RedirectToAction();
         }
    }
}

SmartShop.Web/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartShop.DataLib.Models.Data;
using SmartShop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SmartShop.Web.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly SmartShopDbContext _db;

        public CheckoutController(SmartShopDbContext db)
        {
            _db = db;
        }

        //checkout page
         public IActionResult Index()
         {
             var UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
             var Customer = _db.Customers.Where(x => x.UserId.Equals(UserId)).FirstOrDefault();
             var CustomerId = Customer.CustomerId;
             CheckoutVM checkoutVM = new CheckoutVM()
             {
                 Payments = _db.Payments.ToList(),
                 Shipping = _db.Shippings.ToList(),
                 Total = _db.Carts
                 
                 .Where(x => x.CustomerId.Equals(CustomerId)).Sum(x => x.ProductPrice * x.Quantity),

                 Carts = _db.Carts
            
                 .Where(x => x.CustomerId.Equals(CustomerId))
                 .Include(x => x.Product.ProductImages)
                .Include(x => x.Product.ProductPrices)
                  .Include(x => x.Product)
                  .ThenInclude(x=>x.Brand)
                 .ToList(),
                 Customer = _db.Customers.Where(x => x.CustomerId.Equals(CustomerId)).FirstOrDefault(),


             };
             return View(checkoutVM);
         }
    }
}

SmartShop.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartShop.DataLib.Models.Data;
using SmartShop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartShop.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly SmartShopDbContext _db;
        public ProductController(SmartShopDbContext db)
        {
            this._db = db;
        }

        //product page controller
        public IActionResult Index()
        {
            var Products = _db.Products
                .Include(x=>x.Subcategory.Category)
                .Include(x=>x.Brand)
                .Include(x => x.ProductPrices)
                //.Include(x => x.ProductSpecs)
                .Include(x=>x.Subcategory)
                .Include(x => x.ProductImages)
            

                .ToList();
            return View(Products);
        }
        //product details page
        public IActionResult ProductDetails(int id)
        {
            ProductViewVM productViewVM = new ProductViewVM()
            {
                Product = _db.Products.Where(x => x.ProductId.Equals(id))

                .Include(x => x.Brand)
                .Include(x => x.ProductImages)
                .Include(x => x.Subcategory)
                 .Include(x => x.ProductPrices)
                   .Include(x => x.ProductSpecs)

                .Include(x => x.Reviews)

                .ThenInclude(x => x.Customer)
                .FirstOrDefault(),
                

        };

            return View(productViewVM);
        }
    }
}

SmartShop.Web/Views/Cart/Index.cshtml
@model CartVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="cart mt-5">
    <div class="container ck-cart-info">
        @if (Model.Carts.Count > 0)
        {

            <h5>Your Carts</h5>
            <div class="row">

                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-body">

                            <div class="table-responsive">
                                <table class="table table-borderless">
                                    <thead>
                                        <tr class="text-muted">
                                            <th scope="col">Image</th>
                                            <th scope="col"> Name</th>
                                            <th scope="col">Price</th>

                                            <th scope="col" width="14%">Qty</th>
                                            <th scope="col">Sub Total</th>
                                            <th scope="col">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (var c in Model.Carts)
                                        {


                                        <tr>

                                            <td><img src="http://localhost:5000/Images/@c.Product.ProductImages.First().ImageName" height="80" width="80" /></td>
                                            <td class="align-middle">
                                                @c.Product.ProductName <br />
                                                <p class="text-muted">@c.Product.Brand.BrandName</p>
                                            </td>

                                         
                                         
                                            <td class="align-middle">
                                                $@String.Format("{0:0.00}", c.ProductPrice)
                                              
                                            </td>
                                            <td class="clearfix align-middle">

                                                <form method="post" asp-action="AddQuantity" asp-controller="Cart" asp-route-Id="@c.Product.ProductId">

                                                    <input asp-for="Quantity" class="form-control form-control-sm float-left" style="width: 50px!important;" value="@c.Quantity" />
                                                    <button type="submit" class="btn btn-primary btn-sm rounded-0 float-right" value="Save"><i class="fa fa-save"></i></button>
                                                </form>
                                            </td>
                                            <td class="align-middle">
                                                @{

                                                    var subtotal = c.ProductPrice * c.Quantity;
                                                }
                    
                                                $@String.Format("{0:0.00}", subtotal)
                                            </td>
                                            <td class="align-middle">
                                                <a asp-controller="Cart" asp-action="RemoveCart" asp-route-Id="@c.ProductId" class="btn btn-danger btn-sm rounded-0">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        }




                                    </tbody>
                                </table>

                            </div>









                        </div>


                        <div class="card-footer">
                            <div class="clearfix">
                                <div class="float-left">
                                    <a class="btn btn-info" asp-controller="Product" asp-action="Index">Continue Shopping.....</a>
                                </div>
                                <div class="float-right"><a class="btn btn-dark text-white " asp-action="Index" asp-controller="Checkout">Checkout</a></div>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="clearfix">
                                <div class="float-left">Total Price</div>
                    
                                <div class="float-right">$ @String.Format("{0:0.00}", Model.Total)</div>
                            </div>

                            <div class="clearfix">
                                <div class="float-left">Discount</div>
                                <div class="float-right"> $0</div>
                            </div>

                            <div class="clearfix">
                                <div class="float-left">Total</div>
                                <div class="float-right"><strong>$ @String.Format("{0:0.00}", Model.Total)</strong> </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <img src="~/assets/img/payment.png" style="width:100%;" />
                        </div>
                    </div>
                </div>

            </div>
        }
        else
        {
                                                            <div class="row">
                                                                <div class="col-lg-4 mx-auto">
                                                                    <div class="card">
                                                                        <div class="card-body">
                                                                            <h4 class="text-center text-danger">Empty Cart</h4>
                                                                            <p class="text-center mt-2"><a asp-action="Index" asp-controller="Home" class="btn btn-dark btn-sm">Shop Now</a></p>

                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>


        }

    </div>

</section>